services:

  postgres:
    image: postgres:15
    container_name: invest-user-api-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: invest-user-api
    container_name: invest-user-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:

